# Load packages to extend base R
library("ggplot2")
library("effsize")

# Import data files
# First dataset
d1 <- read.csv(file.choose(), header = TRUE, sep = ",", stringsAsFactors = FALSE)
# Second dataset
d2 <- read.csv(file.choose(), header = TRUE, sep = ",", stringsAsFactors = FALSE)

# User-defined functions
compare <- function(var_name, x = d1[, var_name], y = d2[, var_name]) {
  if(is.character(x) | is.character(y)) {
    if(nlevels(as.factor(x)) <= 5) {
      df <- as.data.frame(table(as.factor(as.vector(as.matrix(x)))))
      df$d <- rep("Original data", nrow(df))
      colnames(df) <- c("level", "count", "d")
      df2 <- as.data.frame(table(as.factor(as.vector(as.matrix(y)))))
      df2$d <- rep("New data", nrow(df))
      colnames(df2) <- c("level", "count", "d")
      df <- rbind(df, df2)
      df$d <- as.factor(df$d)
      df$d <- relevel(df$d, ref = "Original data")
      ggplot(data = df, aes(x = level, y = count, fill = d)) +
        geom_bar(stat = "identity", position = position_dodge()) +
        theme_minimal() + labs(title = paste("Comparison of", var_name, "data", sep = " "), x = "", y = "Count") + 
        theme(legend.position="top") + 
        scale_fill_manual("", values = c("Original data" = "#0C244A", "New data" = "#C5CDDD")) +
        geom_text(data = df, aes(x = level, y = count, label = count), position = position_dodge(width = 0.9), vjust = -0.75) 
    } else {
      sum(x != y, na.rm = TRUE)
    }
  } else {
    x_stats <- paste(format(round(mean(x, na.rm = TRUE), 1), nsmall = 1), "\u00b1", format(round(sd(x, na.rm = TRUE), 1), nsmall = 1), sep = " ")
    # Convert NAs to zeroes so residuals can be calculated
    x[is.na(x)] <- 0
    y_stats <- paste(format(round(mean(y, na.rm = TRUE), 1), nsmall = 1), "\u00b1", format(round(sd(y, na.rm = TRUE), 1), nsmall = 1), sep = " ")
    # Convert NAs to zeroes so residuals can be calculated
    y[is.na(y)] <- 0
    df <- data.frame(x, y)
    df$residuals <- apply(data.frame(x, y), 1, function(x) if(is.na(x[1]) & is.na(x[2])) 0 else x[2] - x[1]  )
    p <- ggplot(df, aes(x, residuals, colour = x))
    p + geom_count(stat = "sum", position = "identity") + theme_minimal() + labs(title = paste("Comparison of", var_name, "data", sep = " "), subtitle = paste(round(sum(df$residuals != 0, na.rm = TRUE) / length(df$residuals) * 100, 2), "%", " disagreement", " (", x_stats, " vs.", y_stats, "; Cohen's d: ", format(round(unname(cohen.d(x, y)$estimate), 2), nsmall = 2),")", sep = ""), x = "Original data", y = "Residuals (new data - original data)") +
      geom_hline(yintercept = 0) + theme(legend.position = "none") +
      annotate("text", 0, 0, vjust = -1, hjust = -0.25, label = "No difference line")
  }
}

# Data analysis
compare("nickname")
compare("test_date")
compare("time_point")
compare("age_years")
compare("age_decimal_years")
compare("age_months")
compare("birth_month")
compare("sex")
compare("school_grade")
compare("province")
compare("country")
compare("location_type")
compare("pe_teacher_credentials")
compare("notes")
compare("sr1")
compare("sr2")
compare("sr_max")
compare("sr_iqr_outliers")
compare("srz")
compare("sr_score")
compare("sr_interpretation")
compare("sr_code")
compare("grip_left1")
compare("grip_left2")
compare("grip_left_max")
compare("grip_right1")
compare("grip_right2")
compare("grip_right_max")
compare("grip_total")
compare("grip_total_iqr_outliers")
compare("grip_totalz")
compare("grip_score")
compare("grip_interpretation")
compare("grip_code")
compare("pacer_distance")
compare("pacer_laps")
compare("pacer_laps_20m")
compare("pacer_laps_iqr_outliers")
compare("pacer_lapsz")
compare("pacer_score")
compare("pacer_interpretation")
compare("pacer_code")
compare("plank_time")
compare("plank_time_iqr_outliers")
compare("plank_timez")
compare("plank_score")
compare("plank_interpretation")
compare("plank_code")
compare("msf_score")
compare("msf_interpretation")
compare("msf_code")
compare("height1")
compare("height2")
compare("height3")
compare("height_average")
compare("height_iqr_outliers")
compare("heightz")
compare("weight1")
compare("weight2")
compare("weight3")
compare("weight_average")
compare("weight_iqr_outliers")
compare("weightz")
compare("bmi")
compare("bmi_iqr_outliers")
compare("bmiz")
compare("bmi_who")
compare("bmi_score")
compare("bmi_interpretation")
compare("bmi_code")
compare("waist1")
compare("waist2")
compare("waist3")
compare("waist_average")
compare("waist_iqr_outliers")
compare("waistz")
compare("waist_score")
compare("waist_interpretation")
compare("waist_code")
compare("body_comp_score")
compare("camsa_time1")
compare("camsa_time_score1")
compare("camsa_skill_score1")
compare("camsa_score1")
compare("jump11")
compare("jump21")
compare("slide11")
compare("slide21")
compare("slide31")
compare("catch1")
compare("throw11")
compare("throw21")
compare("skip11")
compare("skip21")
compare("hop11")
compare("hop21")
compare("kick11")
compare("kick21")
compare("camsa_time2")
compare("camsa_time_score2")
compare("camsa_skill_score2")
compare("camsa_score2")
compare("jump12")
compare("jump22")
compare("slide12")
compare("slide22")
compare("slide32")
compare("catch2")
compare("throw12")
compare("throw22")
compare("skip12")
compare("skip22")
compare("hop12")
compare("hop22")
compare("kick12")
compare("kick22")
compare("best_camsa_score")
compare("best_camsa_score_iqr_outliers")
compare("best_camsa_scorez")
compare("camsa_score")
compare("camsa_interpretation")
compare("camsa_code")
compare("pc_protocol_completes")
compare("pc_completes")
compare("pc_score")
compare("pc_interpretation")
compare("pc_code")
compare("steps1")
compare("time_on1")
compare("time_off1")
compare("non_wear_time1")
compare("time_worn1")
compare("valid_day1")
compare("step_score1")
compare("steps2")
compare("time_on2")
compare("time_off2")
compare("non_wear_time2")
compare("time_worn2")
compare("valid_day2")
compare("step_score2")
compare("steps3")
compare("time_on3")
compare("time_off3")
compare("non_wear_time3")
compare("time_worn3")
compare("valid_day3")
compare("step_score3")
compare("steps4")
compare("time_on4")
compare("time_off4")
compare("non_wear_time4")
compare("time_worn4")
compare("valid_day4")
compare("step_score4")
compare("steps5")
compare("time_on5")
compare("time_off5")
compare("non_wear_time5")
compare("time_worn5")
compare("valid_day5")
compare("step_score5")
compare("steps6")
compare("time_on6")
compare("time_off6")
compare("non_wear_time6")
compare("time_worn6")
compare("valid_day6")
compare("step_score6")
compare("steps7")
compare("time_on7")
compare("time_off7")
compare("non_wear_time7")
compare("time_worn7")
compare("valid_day7")
compare("step_score7")
compare("valid_days")
compare("step_average")
compare("steps_iqr_outliers")
compare("stepsz")
compare("step_score")
compare("step_interpretation")
compare("step_code")
compare("knowledge15")
compare("tv_time_school_day")
compare("knowledge16")
compare("computer_time_school_day")
compare("knowledge17")
compare("tv_time_weekend_day")
compare("knowledge18")
compare("computer_time_weekend_day")
compare("tv_time")
compare("tv_time_iqr_outliers")
compare("tv_timez")
compare("computer_time")
compare("computer_time_iqr_outliers")
compare("computer_timez")
compare("screen_time_average")
compare("screen_time_average_iqr_outliers")
compare("screen_timez")
compare("school_day_screen_time_score")
compare("weekend_day_screen_time_score")
compare("screen_time_score")
compare("screen_time_interpretation")
compare("screen_time_code")
compare("mvpa")
compare("mvpa_iqr_outliers")
compare("mvpaz")
compare("mvpa_score")
compare("mvpa_interpretation")
compare("mvpa_code")
compare("knowledge20")
compare("non_screen_sed_time_school_day")
compare("knowledge_21")
compare("non_screen_sed_time_weekend_day")
compare("non_screen_sed_time")
compare("non_screen_sed_time_iqr_outliers")
compare("non_screen_sed_timez")
compare("non_screen_sed_time_interpretation")
compare("non_screen_sed_time_code")
compare("db_protocol_completes")
compare("db_completes")
compare("db_score")
compare("db_interpretation")
compare("db_code")
compare("knowledge21")
compare("knowledge22")
compare("knowledge23")
compare("knowledge24")
compare("knowledge25")
compare("knowledge26")
compare("knowledge27")
compare("knowledge28")
compare("knowledge29")
compare("benefits")
compare("benefits_iqr_outliers")
compare("benefitsz")
compare("knowledge31")
compare("knowledge32")
compare("knowledge33")
compare("knowledge34")
compare("knowledge35")
compare("knowledge36")
compare("knowledge37")
compare("knowledge38")
compare("knowledge39")
compare("knowledge310")
compare("barriers")
compare("barriers_iqr_outliers")
compare("barriersz")
compare("bb_ratio")
compare("bb_ratio_iqr_outliers")
compare("bb_ratioz")
compare("bb_ratio_score")
compare("bb_ratio_score_iqr_outliers")
compare("bb_ratio_scorez")
compare("bb_ratio_interpretation")
compare("bb_ratio_code")
compare("knowledge4")
compare("compared_to_others_how_active_score")
compare("compared_to_others_how_active_iqr_outliers")
compare("compared_to_others_how_activez")
compare("compared_to_others_how_active_interpretation")
compare("compared_to_others_how_active_code")
compare("knowledge5")
compare("compared_to_others_how_good_at_sport_score")
compare("compared_to_others_how_good_at_sport_iqr_outliers")
compare("compared_to_others_how_good_at_sportz")
compare("compared_to_others_how_good_at_sport_interpretation")
compare("compared_to_others_how_good_at_sport_code")
compare("csappa1")
compare("csappa1_score")
compare("csappa2")
compare("csappa2_score")
compare("csappa3")
compare("csappa3_score")
compare("csappa4")
compare("csappa4_score")
compare("csappa5")
compare("csappa5_score")
compare("csappa6")
compare("csappa6_score")
compare("csappa7")
compare("csappa7_score")
compare("csappa8")
compare("csappa8_score")
compare("csappa9")
compare("csappa9_score")
compare("csappa10")
compare("csappa10_score")
compare("csappa11")
compare("csappa11_score")
compare("csappa12")
compare("csappa12_score")
compare("csappa13")
compare("csappa13_score")
compare("csappa14")
compare("csappa14_score")
compare("csappa15")
compare("csappa15_score")
compare("csappa16")
compare("csappa16_score")
compare("csappa17")
compare("csappa17_score")
compare("csappa_item_completes")
compare("csappa_completes")
compare("adequacy_sum")
compare("adequacy_sum_iqr_outliers")
compare("adequacy_sumz")
compare("adequacy_score")
compare("adequacy_interpretation")
compare("adequacy_code")
compare("predilection_sum")
compare("predilection_sum_iqr_outliers")
compare("predilection_sumz")
compare("predilection_score")
compare("predilection_interpretation")
compare("predilection_code")
compare("mc_protocol_completes")
compare("mc_completes")
compare("mc_score")
compare("mc_interpretation")
compare("mc_code")
compare("knowledge1")
compare("knowledge1_score")
compare("knowledge6")
compare("knowledge6_score")
compare("knowledge7")
compare("knowledge7_score")
compare("knowledge8")
compare("knowledge8_score")
compare("knowledge91")
compare("knowledge92")
compare("knowledge93")
compare("knowledge94")
compare("knowledge95")
compare("healthy_means_score")
compare("knowledge101")
compare("knowledge102")
compare("knowledge103")
compare("knowledge104")
compare("knowledge105")
compare("fill_in_the_blanks_score")
compare("knowledge11_snowmobile")
compare("knowledge11_snowmobile_safety_gear")
compare("knowledge11_swing")
compare("knowledge11_swing_safety_gear")
compare("knowledge11_baseball")
compare("knowledge11_baseball_safety_gear")
compare("knowledge11_toboggan")
compare("knowledge11_toboggan_safety_gear")
compare("knowledge11_bars")
compare("knowledge11_bars_safety_gear")
compare("knowledge11_skip")
compare("knowledge11_skip_safety_gear")
compare("knowledge11_swim")
compare("knowledge11_swim_safety_gear")
compare("knowledge11_inline_skate")
compare("knowledge11_inline_skate_safety_gear")
compare("knowledge11_xcountry_ski")
compare("knowledge11_xcountry_ski_safety_gear")
compare("knowledge11_bike")
compare("knowledge11_bike_safety_gear")
compare("knowledge11_skate")
compare("knowledge11_skate_safety_gear")
compare("activities_score")
compare("knowledge12")
compare("knowledge12_score")
compare("knowledge13")
compare("knowledge13_score")
compare("knowledge14")
compare("knowledge14_score")
compare("ku_protocol_completes")
compare("ku_completes")
compare("ku_score")
compare("ku_interpretation")
compare("ku_code")
compare("domain_completes")
compare("capl_completes")
compare("capl_score")
compare("capl_interpretation")
compare("capl_code")